import Link from "@docusaurus/Link";

const types = {
  void: "https://docs.oracle.com/javase/8/docs/api/java/lang/Void.html",
  int: "https://docs.oracle.com/javase/7/docs/api/java/lang/Integer.html",
  float: "https://docs.oracle.com/javase/7/docs/api/java/lang/Float.html",
  String: "https://docs.oracle.com/javase/7/docs/api/java/lang/String.html",
  boolean: "https://docs.oracle.com/javase/7/docs/api/java/lang/Boolean.html",
  double: "https://docs.oracle.com/javase/7/docs/api/java/lang/Double.html",
  Object: "https://docs.oracle.com/javase/7/docs/api/java/lang/Object.html",
  char: "https://docs.oracle.com/javase/7/docs/api/java/lang/Character.html",
  byte: "https://docs.oracle.com/javase/7/docs/api/java/lang/Byte.html",
  short: "https://docs.oracle.com/javase/7/docs/api/java/lang/Short.html",
  long: "https://docs.oracle.com/javase/7/docs/api/java/lang/Long.html",
  FloatBuffer: "https://docs.oracle.com/javase/7/docs/api/java/nio/FloatBuffer.html",
  ByteBuffer: "https://docs.oracle.com/javase/7/docs/api/java/nio/ByteBuffer.html",
  IntBuffer: "https://docs.oracle.com/javase/7/docs/api/java/nio/IntBuffer.html",
  ShortBuffer: "https://docs.oracle.com/javase/7/docs/api/java/nio/ShortBuffer.html",
  LongBuffer: "https://docs.oracle.com/javase/7/docs/api/java/nio/LongBuffer.html",
  DoubleBuffer: "https://docs.oracle.com/javase/7/docs/api/java/nio/DoubleBuffer.html",
  CharBuffer: "https://docs.oracle.com/javase/7/docs/api/java/nio/CharBuffer.html",
  List: "https://docs.oracle.com/javase/7/docs/api/java/util/List.html",
  ArrayList: "https://docs.oracle.com/javase/7/docs/api/java/util/ArrayList.html",
  Map: "https://docs.oracle.com/javase/7/docs/api/java/util/Map.html",
  HashMap: "https://docs.oracle.com/javase/7/docs/api/java/util/HashMap.html",
  PerlinNoise: "/docs/java/Algorithms/PerlinNoise",
  AButton: "/docs/java/Android Views/AButton",
  ACheckBox: "/docs/java/Android Views/ACheckBox",
  AConstraintLayout: "/docs/java/Android Views/AConstraintLayout",
  AABB: "/docs/java/Vector/AABB",
  AbstractCameraObjectFilter: "/docs/java/Utils/AbstractCameraObjectFilter",
  AEditText: "/docs/java/Android Views/AEditText",
  AImageButton: "/docs/java/Android Views/AImageButton",
  AImageView: "/docs/java/Android Views/AImageView",
  ALayoutInflater: "/docs/java/Android Views/ALayoutInflater",
  ALinearLayout: "/docs/java/Android Views/ALinearLayout",
  AList: "/docs/java/Lists/AList",
  AListView: "/docs/java/Android Views/AListView",
  AmbientLight: "/docs/java/Components/Post processing/AmbientLight",
  Animation: "/docs/java/Animations/Animation",
  AnimationFile: "/docs/java/Animations/AnimationFile",
  AnimationPlayer: "/docs/java/Components/Animations/AnimationPlayer",
  AnimationTransition: "/docs/java/Animations/AnimationTransition",
  AnimationTrigger: "/docs/java/Components/TODO/AnimationTrigger",
  AOnClickListener: "/docs/java/Android Views/AOnClickListener",
  AOnCreateContextMenuListener: "/docs/java/Android Views/AOnCreateContextMenuListener",
  AOnDragListener: "/docs/java/Android Views/AOnDragListener",
  AOnEditorActionListener: "/docs/java/Android Views/AOnEditorActionListener",
  AOnFocusChangeListener: "/docs/java/Android Views/AOnFocusChangeListener",
  AOnGenericMotionListener: "/docs/java/Android Views/AOnGenericMotionListener",
  AOnHoverListener: "/docs/java/Android Views/AOnHoverListener",
  AOnItemClickListener: "/docs/java/Android Views/AOnItemClickListener",
  AOnItemLongClickListener: "/docs/java/Android Views/AOnItemLongClickListener",
  AOnItemSelectedListener: "/docs/java/Android Views/AOnItemSelectedListener",
  AOnKeyListener: "/docs/java/Android Views/AOnKeyListener",
  AOnLongClickListener: "/docs/java/Android Views/AOnLongClickListener",
  AOnScrollChangeListener: "/docs/java/Android Views/AOnScrollChangeListener",
  AOnTouchListener: "/docs/java/Android Views/AOnTouchListener",
  AProgressBar: "/docs/java/Android Views/AProgressBar",
  ARadioButton: "/docs/java/Android Views/ARadioButton",
  AreaTrigger: "/docs/java/Physics/AreaTrigger",
  ARelativeLayout: "/docs/java/Android Views/ARelativeLayout",
  Armature: "/docs/java/Components/Armature",
  ASeekBar: "/docs/java/Android Views/ASeekBar",
  ASpinner: "/docs/java/Android Views/ASpinner",
  ASwitch: "/docs/java/Android Views/ASwitch",
  AsyncLaserListener: "/docs/java/Vertex/AsyncLaserListener",
  AsyncRunnable: "/docs/java/Async/AsyncRunnable",
  AsyncTask: "/docs/java/Async/AsyncTask",
  ATextView: "/docs/java/Android Views/ATextView",
  AtmosphericScattering: "/docs/java/Components/Post processing/AtmosphericScattering",
  AtomicBoolean: "/docs/java/Atomic/AtomicBoolean",
  AtomicFloat: "/docs/java/Atomic/AtomicFloat",
  AtomicInteger: "/docs/java/Atomic/AtomicInteger",
  AudioEffect: "/docs/java/SoundEffects/AudioEffect",
  AutoWired: "/docs/java/Uncategorized/AutoWired",
  AView: "/docs/java/Android Views/AView",
  AViewInstance: "/docs/java/Android Views/AViewInstance",
  AWebView: "/docs/java/Android Views/AWebView",
  Axis: "/docs/java/Input/Axis",
  BassBoostEffect: "/docs/java/SoundEffects/BassBoostEffect",
  Billboard: "/docs/java/Components/TODO/Billboard",
  Bloom: "/docs/java/Components/Post processing/Bloom",
  Brush: "/docs/java/Brush/Brush",
  BufferUtils: "/docs/java/Buffers/BufferUtils",
  Camera: "/docs/java/Components/Rendering/Camera",
  CameraObjectFilter: "/docs/java/CameraFilters/CameraObjectFilter",
  Characterbody: "/docs/java/Physics/Characterbody",
  ChromaticAberration: "/docs/java/Components/Post processing/ChromaticAberration",
  CircleBrush: "/docs/java/Brushs/CircleBrush",
  ClassCategory: "/docs/java/Uncategorized/ClassCategory",
  Collider: "/docs/java/Components/Physics/Collider",
  Collision: "/docs/java/Physics/Collision",
  Color: "/docs/java/Vector/Color",
  ColorGradient: "/docs/java/Vector/ColorGradient",
  CompileErrorListener: "/docs/java/Shaders/CompileErrorListener",
  Component: "/docs/java/Components/Component",
  ComponentInspector: "/docs/java/Editor/ComponentInspector",
  CompoundVertex: "/docs/java/Uncategorized/CompoundVertex",
  ConnectionListener: "/docs/java/Uncategorized/ConnectionListener",
  ConstraintPivot: "/docs/java/Components/Constraint/ConstraintPivot",
  ContactShadows: "/docs/java/Components/Post processing/ContactShadows",
  Curve: "/docs/java/Vector/Curve",
  CustomAmbientLight: "/docs/java/Components/Post processing/CustomAmbientLight",
  CustomPostProcessing: "/docs/java/Components/Post processing/CustomPostProcessing",
  CustomSkybox: "/docs/java/Components/Post processing/CustomSkybox",
  DatagramSocket: "/docs/java/Uncategorized/DatagramSocket",
  DeprecatedInfo: "/docs/java/Uncategorized/DeprecatedInfo",
  DepthOfField: "/docs/java/Components/Post processing/DepthOfField",
  Device: "/docs/java/Platform/Device",
  Directories: "/docs/java/Platform/Directories",
  DivEqualOperator: "/docs/java/EngineOverride/DivEqualOperator",
  DivOperator: "/docs/java/EngineOverride/DivOperator",
  Easings: "/docs/java/Math/Easings",
  Editor: "/docs/java/Editor/Editor",
  EditorPanel: "/docs/java/Editor/EditorPanel",
  EnemyAITypeA: "/docs/java/Components/AI/EnemyAITypeA",
  EqualizerEffect: "/docs/java/SoundEffects/EqualizerEffect",
  EqualsComparator: "/docs/java/EngineOverride/EqualsComparator",
  ExecutionAllow: "/docs/java/Uncategorized/ExecutionAllow",
  File: "/docs/java/Files/File",
  FileLoader: "/docs/java/Files/FileLoader",
  FilePicker: "/docs/java/Uncategorized/FilePicker",
  FilesPanelCustomIcon: "/docs/java/Files/FilesPanelCustomIcon",
  FilesPanelDirectoryMenu: "/docs/java/Files/FilesPanelDirectoryMenu",
  FilesPanelFileMenu: "/docs/java/Files/FilesPanelFileMenu",
  FileUtils: "/docs/java/Files/FileUtils",
  FilmGrainScratch: "/docs/java/Components/Post processing/FilmGrainScratch",
  FixedFrameListener: "/docs/java/Framerate/FixedFrameListener",
  FixedFraming: "/docs/java/Framerate/FixedFraming",
  FloatingPanelArea: "/docs/java/Uncategorized/FloatingPanelArea",
  FloatSlider: "/docs/java/Inspector/FloatSlider",
  Fog: "/docs/java/Components/Post processing/Fog",
  Font: "/docs/java/Fonts/Font",
  FontFile: "/docs/java/Fonts/FontFile",
  FontLoader: "/docs/java/Fonts/FontLoader",
  FormatDictionaries: "/docs/java/Files/FormatDictionaries",
  FrameBuffer: "/docs/java/Shaders/FrameBuffer",
  GalleryPicker: "/docs/java/Uncategorized/GalleryPicker",
  GameController: "/docs/java/Platform/GameController",
  GamePadButton: "/docs/java/Input/GamePadButton",
  GaussianBlur: "/docs/java/Components/TODO/GaussianBlur",
  Gizmo: "/docs/java/Debug/Gizmo",
  GizmoElement: "/docs/java/Debug/GizmoElement",
  GizmoMatrix: "/docs/java/Debug/GizmoMatrix",
  GizmoObject: "/docs/java/Debug/GizmoObject",
  GizmoObjectMatrix: "/docs/java/Debug/GizmoObjectMatrix",
  GizmoPath: "/docs/java/Debug/GizmoPath",
  GizmoTransform: "/docs/java/Debug/GizmoTransform",
  GradientLight: "/docs/java/Components/Post processing/GradientLight",
  GradientSkybox: "/docs/java/Components/Post processing/GradientSkybox",
  GraphicsSettings: "/docs/java/World/GraphicsSettings",
  GreaterThanComparator: "/docs/java/EngineOverride/GreaterThanComparator",
  Group: "/docs/java/Uncategorized/Group",
  GUID: "/docs/java/Uncategorized/GUID",
  GUIUtils: "/docs/java/GUI/GUIUtils",
  Hide: "/docs/java/Uncategorized/Hide",
  HideGetSet: "/docs/java/Uncategorized/HideGetSet",
  HingeConstraint: "/docs/java/Components/Constraint/HingeConstraint",
  IllegalBufferException: "/docs/java/Uncategorized/IllegalBufferException",
  IllegalOperatorException: "/docs/java/Uncategorized/IllegalOperatorException",
  IllegalPFileUseException: "/docs/java/Uncategorized/IllegalPFileUseException",
  InaccessibleFilePathException: "/docs/java/Uncategorized/InaccessibleFilePathException",
  Input: "/docs/java/Input/Input",
  InputDialog: "/docs/java/Input/InputDialog",
  InputDialogListener: "/docs/java/Input/InputDialogListener",
  InspectorMemory: "/docs/java/Platform/InspectorMemory",
  IntSlider: "/docs/java/Inspector/IntSlider",
  InvalidStateException: "/docs/java/Uncategorized/InvalidStateException",
  InvokeListener: "/docs/java/Uncategorized/InvokeListener",
  JavaPool: "/docs/java/Uncategorized/JavaPool",
  JavaThermalFlowStatics: "/docs/java/ThermalFlow/JavaThermalFlowStatics",
  JavaUtils: "/docs/java/Java/JavaUtils",
  JClass: "/docs/java/Java/JClass",
  JCompiler: "/docs/java/Java/JCompiler",
  JRDoc_EN: "/docs/java/Uncategorized/JRDoc_EN",
  JRDoc_PT: "/docs/java/Uncategorized/JRDoc_PT",
  Json: "/docs/java/Serializer/Json",
  JsonSerializer: "/docs/java/Uncategorized/JsonSerializer",
  Key: "/docs/java/Input/Key",
  KeyboardButton: "/docs/java/Input/KeyboardButton",
  KeyboardMapper: "/docs/java/Components/Input/KeyboardMapper",
  Laser: "/docs/java/Laser/Laser",
  LaserHit: "/docs/java/Laser/LaserHit",
  LensDistortion: "/docs/java/Components/Post processing/LensDistortion",
  LessThanComparator: "/docs/java/EngineOverride/LessThanComparator",
  Listener: "/docs/java/Uncategorized/Listener",
  ListStream: "/docs/java/Lists/ListStream",
  ListStreamListener: "/docs/java/Lists/ListStreamListener",
  LOD: "/docs/java/Components/TODO/LOD",
  LODTarget: "/docs/java/Components/TODO/LODTarget",
  Log: "/docs/java/Debug/Log",
  LooperThread: "/docs/java/Uncategorized/LooperThread",
  LuaComponent: "/docs/java/Components/Lua/LuaComponent",
  Map2: "/docs/java/Lists/Map2",
  Matcap: "/docs/java/Uncategorized/Matcap",
  Material: "/docs/java/Material",
  MaterialFile: "/docs/java/Material/MaterialFile",
  Math: "/docs/java/Math/Math",
  Matrix4: "/docs/java/Vector/Matrix4",
  MeshCurve: "/docs/java/Components/Roads/MeshCurve",
  MethodArgs: "/docs/java/Uncategorized/MethodArgs",
  MicrophoneReader: "/docs/java/Components/Sound/MicrophoneReader",
  ModelRenderer: "/docs/java/Components/Rendering/ModelRenderer",
  ModEqualOperator: "/docs/java/EngineOverride/ModEqualOperator",
  ModOperator: "/docs/java/EngineOverride/ModOperator",
  MotionBlur: "/docs/java/Components/TODO/MotionBlur",
  MulEqualOperator: "/docs/java/EngineOverride/MulEqualOperator",
  MulOperator: "/docs/java/EngineOverride/MulOperator",
  NativeByteBuffer: "/docs/java/Buffers/NativeByteBuffer",
  NativeCharBuffer: "/docs/java/Buffers/NativeCharBuffer",
  NativeFloatBuffer: "/docs/java/Buffers/NativeFloatBuffer",
  NativeIntBuffer: "/docs/java/Buffers/NativeIntBuffer",
  NativeShortBuffer: "/docs/java/Buffers/NativeShortBuffer",
  NavMesh: "/docs/java/Components/AI/NavMesh",
  NightVision: "/docs/java/Components/Post processing/NightVision",
  NoHitException: "/docs/java/Uncategorized/NoHitException",
  NurbsPath2D: "/docs/java/NurbsPath/NurbsPath2D",
  NurbsPath3D: "/docs/java/NurbsPath/NurbsPath3D",
  ObjectFile: "/docs/java/Files/ObjectFile",
  ObjectPool: "/docs/java/Components/ObjectPool",
  ObjectsPanelMenu: "/docs/java/Uncategorized/ObjectsPanelMenu",
  OH2LevelFloatArray: "/docs/java/Buffers/OH2LevelFloatArray",
  OH2LevelIntArray: "/docs/java/Buffers/OH2LevelIntArray",
  OH3LevelFloatArray: "/docs/java/Buffers/OH3LevelFloatArray",
  OH3LevelIntArray: "/docs/java/Buffers/OH3LevelIntArray",
  OHDataBase: "/docs/java/Buffers/OHDataBase",
  OHFloatDataBase: "/docs/java/Buffers/OHFloatDataBase",
  OHIntDataBase: "/docs/java/Buffers/OHIntDataBase",
  OHString: "/docs/java/Buffers/OHString",
  Order: "/docs/java/Uncategorized/Order",
  Outline: "/docs/java/Components/TODO/Outline",
  OutPFile: "/docs/java/Files/OutPFile",
  OutputVideoFile: "/docs/java/Files/OutputVideoFile",
  PanelArea: "/docs/java/Uncategorized/PanelArea",
  PanelInflateMenu: "/docs/java/Uncategorized/PanelInflateMenu",
  Particle: "/docs/java/Uncategorized/Particle",
  ParticleConeShapeOptions: "/docs/java/Particles/ParticleConeShapeOptions",
  ParticleEmitter: "/docs/java/Components/Particles/ParticleEmitter",
  ParticleSphereShapeOptions: "/docs/java/Particles/ParticleSphereShapeOptions",
  PathFinder: "/docs/java/Components/AI/PathFinder",
  PhysicsComponent: "/docs/java/Components/Physics/PhysicsComponent",
  PhysicsLayer: "/docs/java/Uncategorized/PhysicsLayer",
  PhysicsLayers: "/docs/java/Uncategorized/PhysicsLayers",
  PhysicsSettings: "/docs/java/Physics/PhysicsSettings",
  Point2: "/docs/java/Vector/Point2",
  Point2Buffer: "/docs/java/Vector/Point2Buffer",
  Point3: "/docs/java/Vector/Point3",
  Point3Buffer: "/docs/java/Vector/Point3Buffer",
  PointConstraint: "/docs/java/Components/Constraint/PointConstraint",
  PointLight: "/docs/java/Components/Light/PointLight",
  PopupDialog: "/docs/java/Input/PopupDialog",
  PopupDialogListener: "/docs/java/Input/PopupDialogListener",
  PostVignette: "/docs/java/Components/Post processing/PostVignette",
  ProjectFile: "/docs/java/Files/ProjectFile",
  PropertiesButton: "/docs/java/Inspector/PropertiesButton",
  PropertiesButtonListener: "/docs/java/Inspector/PropertiesButtonListener",
  Quaternion: "/docs/java/Vector/Quaternion",
  Random: "/docs/java/Math/Random",
  Ray: "/docs/java/Laser/Ray",
  RayDirection: "/docs/java/Laser/RayDirection",
  ReadOnly: "/docs/java/Uncategorized/ReadOnly",
  RemoveRemoveOperator: "/docs/java/EngineOverride/RemoveRemoveOperator",
  RenderEffectArea: "/docs/java/Components/Post processing/RenderEffectArea",
  RenderTextureExtractor: "/docs/java/Components/Render/RenderTextureExtractor",
  Resources: "/docs/java/Uncategorized/Resources",
  Rigidbody: "/docs/java/Physics/Rigidbody",
  Road: "/docs/java/Components/Roads/Road",
  RoadPoint: "/docs/java/Components/Roads/RoadPoint",
  RoomNotConnectedException: "/docs/java/Uncategorized/RoomNotConnectedException",
  RoomNotDisconnectedException: "/docs/java/Uncategorized/RoomNotDisconnectedException",
  Route: "/docs/java/Components/AI/Route",
  RouteFollower: "/docs/java/Components/AI/RouteFollower",
  Runnable: "/docs/java/Thread/Runnable",
  Saveable: "/docs/java/Uncategorized/Saveable",
  SaveGame: "/docs/java/SaveGame/SaveGame",
  ScaleBasedDistance: "/docs/java/Components/TODO/ScaleBasedDistance",
  Screen: "/docs/java/Platform/Screen",
  ScriptingExtension: "/docs/java/Uncategorized/ScriptingExtension",
  ServerSocket: "/docs/java/Uncategorized/ServerSocket",
  Sharpen: "/docs/java/Components/TODO/Sharpen",
  ShortVector3Buffer: "/docs/java/Vector/ShortVector3Buffer",
  SimpleEnemyAI: "/docs/java/Components/AI/SimpleEnemyAI",
  Singleton: "/docs/java/Uncategorized/Singleton",
  SkinJoint: "/docs/java/Components/Skin/SkinJoint",
  SkinnedModelRenderer: "/docs/java/Components/Rendering/SkinnedModelRenderer",
  Skybox: "/docs/java/Components/Post processing/Skybox",
  SlideRotate: "/docs/java/Components/Prototyping/SlideRotate",
  SmoothCameraFollow: "/docs/java/Components/Prototyping/SmoothCameraFollow",
  Socket: "/docs/java/Uncategorized/Socket",
  SoundData: "/docs/java/Uncategorized/SoundData",
  SoundDecoder: "/docs/java/Uncategorized/SoundDecoder",
  SoundEmitter: "/docs/java/Uncategorized/SoundEmitter",
  SoundFile: "/docs/java/Files/SoundFile",
  SoundListener: "/docs/java/Components/Sound/SoundListener",
  SoundPlayer: "/docs/java/Components/Sound/SoundPlayer",
  SpatialObject: "/docs/java/Object/SpatialObject",
  SpotLight: "/docs/java/Components/Light/SpotLight",
  SquareBrush: "/docs/java/Brush/SquareBrush",
  SSAO: "/docs/java/Components/Post processing/SSAO",
  SSR: "/docs/java/Components/Post processing/SSR",
  StandUp: "/docs/java/Components/Prototyping/StandUp",
  StringOperations: "/docs/java/String/StringOperations",
  SubEqualOperator: "/docs/java/EngineOverride/SubEqualOperator",
  SubOperator: "/docs/java/EngineOverride/SubOperator",
  SumEqualOperator: "/docs/java/EngineOverride/SumEqualOperator",
  SumOperator: "/docs/java/EngineOverride/SumOperator",
  SunLight: "/docs/java/Components/Light/SunLight",
  SynchronizedArrayList: "/docs/java/Lists/SynchronizedArrayList",
  SynchronizedLinkedList: "/docs/java/Lists/SynchronizedLinkedList",
  SynchronizedList: "/docs/java/Lists/SynchronizedList",
  System: "/docs/java/Uncategorized/System",
  TagEnemyFieldOfView: "/docs/java/Prototyping/TagEnemyFieldOfView",
  Terminal: "/docs/java/Debug/Terminal",
  TerminalCLIExtension: "/docs/java/Uncategorized/TerminalCLIExtension",
  Terrain: "/docs/java/Components/Terrain",
  TextScriptingExtension: "/docs/java/Uncategorized/TextScriptingExtension",
  TextScriptingProvider: "/docs/java/Uncategorized/TextScriptingProvider",
  TextScriptingStyler: "/docs/java/Uncategorized/TextScriptingStyler",
  TextScriptingStyleSpan: "/docs/java/Uncategorized/TextScriptingStyleSpan",
  TextScriptingSuggestion: "/docs/java/Uncategorized/TextScriptingSuggestion",
  TextScriptingSyntaxHighlightSpan: "/docs/java/Uncategorized/TextScriptingSyntaxHighlightSpan",
  TextScriptingTheme: "/docs/java/Uncategorized/TextScriptingTheme",
  Texture: "/docs/java/Material/Texture",
  TextureFile: "/docs/java/Material/TextureFile",
  ThermalFlowError: "/docs/java/Uncategorized/ThermalFlowError",
  Thread: "/docs/java/Thread/Thread",
  Time: "/docs/java/Time/Time",
  TimeCounter: "/docs/java/Time/TimeCounter",
  Toast: "/docs/java/Input/Toast",
  ToneMapper: "/docs/java/Components/Post processing/ToneMapper",
  Touch: "/docs/java/Input/Touch",
  Transform: "/docs/java/Object/Transform",
  UI3DCameraAimInputSystem: "/docs/java/Components/UI/UI3DCameraAimInputSystem",
  UI3DInputSystem: "/docs/java/Components/UI/UI3DInputSystem",
  UIAlignment: "/docs/java/Components/UI/UIAlignment",
  UIAnchor: "/docs/java/Components/UI/UIAnchor",
  UIAspectRatio: "/docs/java/Components/UI/UIAspectRatio",
  UIAxisEventListener: "/docs/java/Components/UI/UIAxisEventListener",
  UIBackgroundBlur: "/docs/java/Components/Post processing/UIBackgroundBlur",
  UIBarHandler: "/docs/java/Components/TODO/UIBarHandler",
  UIBloom: "/docs/java/Components/Post processing/UIBloom",
  UIButton: "/docs/java/Components/UI/UIButton",
  UICheckBox: "/docs/java/Components/UI/UICheckBox",
  UIChromaticAberration: "/docs/java/Components/Post processing/UIChromaticAberration",
  UIContrastBrightnessSaturation: "/docs/java/Components/Post processing/UIContrastBrightnessSaturation",
  UIController: "/docs/java/Components/UI/UIController",
  UICustomPostProcessing: "/docs/java/Components/Post processing/UICustomPostProcessing",
  UIDrivingWheel: "/docs/java/Components/UI/UIDrivingWheel",
  UIDynamicJoystick: "/docs/java/Components/UI/UIDynamicJoystick",
  UIFadeOut: "/docs/java/Components/Post processing/UIFadeOut",
  UIFitParent: "/docs/java/Components/UI/UIFitParent",
  UIFlexLayout: "/docs/java/Components/UI/UIFlexLayout",
  UIGaussianBlur: "/docs/java/Components/Post processing/UIGaussianBlur",
  UIGridLayout: "/docs/java/Components/UI/UIGridLayout",
  UIHorizontalLayout: "/docs/java/Components/UI/UIHorizontalLayout",
  UIHorizontalScrollView: "/docs/java/Components/UI/UIHorizontalScrollView",
  UIHoverButton: "/docs/java/Components/UI/UIHoverButton",
  UIImage: "/docs/java/Components/UI/UIImage",
  UIInputText: "/docs/java/Components/UI/UIInputText",
  UIJoystick: "/docs/java/Components/UI/UIJoystick",
  UIKeyEventListener: "/docs/java/Components/UI/UIKeyEventListener",
  UIOutline: "/docs/java/Components/Post processing/UIOutline",
  UIPostTransform: "/docs/java/Components/Post processing/UIPostTransform",
  UIPostVignette: "/docs/java/Components/Post processing/UIPostVignette",
  UIProgressBar: "/docs/java/Components/UI/UIProgressBar",
  UIRadioButton: "/docs/java/Components/UI/UIRadioButton",
  UIRadioGroup: "/docs/java/Components/UI/UIRadioGroup",
  UIRect: "/docs/java/Components/UI/UIRect",
  UIRectangularMask: "/docs/java/Components/UI/UIRectangularMask",
  UIRotateImage: "/docs/java/Components/UI/UIRotateImage",
  UIShape: "/docs/java/Components/UI/UIShape",
  UISharpen: "/docs/java/Components/Post processing/UISharpen",
  UISlideArea: "/docs/java/Components/UI/UISlideArea",
  UISlideBar: "/docs/java/Components/TODO/UISlideBar",
  UITextView: "/docs/java/Components/UI/UITextView",
  UITouchTrigger: "/docs/java/Components/UI/UITouchTrigger",
  UIVerticalLayout: "/docs/java/Components/UI/UIVerticalLayout",
  UIVerticalScrollView: "/docs/java/Components/UI/UIVerticalScrollView",
  UIVHSFilter: "/docs/java/Components/Post processing/UIVHSFilter",
  UIWeight: "/docs/java/Components/UI/UIWeight",
  ValueObject: "/docs/java/Uncategorized/ValueObject",
  Vector2: "/docs/java/Vector/Vector2",
  Vector2Buffer: "/docs/java/Vector/Vector2Buffer",
  Vector3: "/docs/java/Vector/Vector3",
  Vector3Buffer: "/docs/java/Vector/Vector3Buffer",
  Vector4: "/docs/java/Vector/Vector4",
  VehiclePhysics: "/docs/java/Components/Physics/VehiclePhysics",
  VehicleWheel: "/docs/java/Components/Physics/VehicleWheel",
  Vertex: "/docs/java/Vertex",
  VertexFile: "/docs/java/Files/VertexFile",
  VHSFilter: "/docs/java/Components/Post processing/VHSFilter",
  VideoFile: "/docs/java/Files/VideoFile",
  VideoPlayer: "/docs/java/Components/Sound/VideoPlayer",
  ViewPanel: "/docs/java/Editor/ViewPanel",
  Vignette: "/docs/java/Components/Post processing/Vignette",
  VoxelChunk: "/docs/java/Components/Voxels/VoxelChunk",
  VoxelChunkSpawner: "/docs/java/Components/Voxels/VoxelChunkSpawner",
  VoxelCollider: "/docs/java/Components/Voxels/VoxelCollider",
  VoxelGenerator: "/docs/java/Components/Voxels/VoxelGenerator",
  VoxelGeneratorListener: "/docs/java/Uncategorized/VoxelGeneratorListener",
  VoxelGeneratorListenerV2: "/docs/java/Uncategorized/VoxelGeneratorListenerV2",
  VoxelHand: "/docs/java/Components/Voxels/VoxelHand",
  VoxelPhysics: "/docs/java/Components/Voxels/VoxelPhysics",
  VoxelPlayerController: "/docs/java/Components/Voxels/VoxelPlayerController",
  VoxelVertexGeneratorListener: "/docs/java/Uncategorized/VoxelVertexGeneratorListener",
  WatchedObject: "/docs/java/Uncategorized/WatchedObject",
  World: "/docs/java/World/World",
  WorldController: "/docs/java/World/WorldController",
  WorldFile: "/docs/java/World/WorldFile",
  AddAddOperator: "/docs/java/EngineOverride/AddAddOperator",
};

export default function Type({ name }) {
  const href = types[name];
  if (!href) return <code>{name}</code>;

  return (
    <Link to={href}>
      <code>{name}</code>
    </Link>
  );
}
